### PR TITLE
Add a simple function for retrieving all the jobs in the system

### PR DESCRIPTION
**Pull request by renatoc-br**

### CODE REVIEW

**Comment by adamsla** [comment]
Hi, can you please sign off on the pull request.  Simply read the modified DCO and update the pull request comments with the Signed-off-by line.  Thanks!

**Comment by PlatformLSF** [comment]
Hello  renatoc-br, could you please sign off on the pull request ? Thanks.

**Comment by PlatformLSF** [comment]
Closing due to lack of response

**Comment by adamsla** [comment]
@PlatformLSF, please reopen.  The original pull request author @ghost, and IBMer, was not properly tracking this.  He just posted on Slack, and I pointed out that he did not follow the process.

**Comment by adamsla** [comment]
@PlatformLSF, I had a followup with the customer and it appears he wrote his own thing.  Has this functionality been merged by others yet?  He was peaking specifically about the jobInfo structure (bjobs equivalent in Python).  He claimed it was not in the Python API.

**Pull request closed without merging**
