### PR TITLE
Add a function to retrieve a conf value

### PR DESCRIPTION
**Pull request by mattaezell**
This retrieves a single conf value from `lsf.conf`

### CODE REVIEW

**Comment by adamsla** [comment]
Matt,

Can you please post a comment with your signoff per the DCO.  It's pretty simple.  Just follow the one line instructions in the DCO document in the root of the repo.

Thanks,

Larry

**Comment by mattaezell** [comment]
Hi @adamsla,
I included the DCO in my commit message (as many other projects require), but happy to also include it as a comment here.  Thanks!

Signed-off-by: Matt Ezell <ezellma@ornl.gov>

**Comment by adamsla** [comment]
Thanks Matt!

**Comment by mattaezell** [comment]
Could someone review this code for potential inclusion?

**Comment by adamsla** [comment]
Sorry Matt.  The dev team moves slowly some times on these things.  I'll ping them.  This setting seems innocuous enough.

**Comment by PlatformLSF** [comment]
The code is reviewed. It's OK.

**Pull request merged**
